name: Stats Chart Updater

on:
  schedule:
    - cron: '0 0 1 * *' # runs every month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - uses: lnxpy/pypi-stats-viewer@v1
        with:
          package: hey-mindsdb
          output: media/stats.svg
          theme: plotly_dark

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: chart is updated
